apiVersion: apps/v1
kind: Deployment
metadata:
  name: advproject
spec:
  selector:
    matchLabels:
      app: advproject
  replicas: 2
  template:
    metadata:
      labels:
        app: advproject
    spec:
      containers:
      - name: advproject
        image: ccr.ccs.tencentyun.com/darkreunion/advproject:build-{buildID}
        env:
          - name: RUN_MODE
            value: "prod"
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 30
      imagePullSecrets:
        - name: registry-secret
