basePath: /api/v1
definitions:
  serializer.Response:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
      result:
        type: boolean
    type: object
info:
  contact:
    email: wanghaoxi3000@163.com
    name: wanghaoxi3000
  description: advanced project
  title: API doc
  version: "1.0"
paths:
  /hostname:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 主机标识
      tags:
      - status
  /status:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 状态输出
      tags:
      - status
swagger: "2.0"
